=== Politecnicojic2022-01/Marcadores/marcadores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pagina" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="url" type="xs:string"/>
                            <xs:element name="aÃ±o">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="2000"/>
                                        <xs:maxInclusive value="2050"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ssl" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Politecnicojic2022-01/Marcadores/Marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="marcadores.xsd">
    <pagina ssl="true">
        <nombre>Abrirllave</nombre>
        <descripcion>Tutoriales de informática.</descripcion>
        <url>http://www.abrirllave.com/</url>
        <año>2005</año>
    </pagina>
    <pagina ssl="true">
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre.</descripcion>
        <url>http://www.wikipedia.org/</url>
        <año>2040</año>
    </pagina>
    <pagina ssl="true">
        <nombre>W3C</nombre>
        <descripcion>World Wide Web Consortium.</descripcion>
        <url>http://www.w3.org/</url>
        <año>2005</año>
    </pagina>
</marcadores>
